Procedure:
  moderation:
    silent-ban: true
    silent-kick: false
  gui:
    scaled-size: THREE
    single-size: THREE
Format:
  groups:
    Default:
      color: '&f'
      prefix: '&7[&fDefault&7]'
    Admin:
      color: '&c'
      prefix: '&7[&cAdmin&7]'