name: myEssentials
version: 1.0.0
main: com.github.sanctum.myessentials.Essentials
api-version: 1.13
author: ${parent.organization.name}
description: ${parent.description}
website: ${parent.organization.url}
depend: [ Labyrinth ]